modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="test_remote_work"
version="1.0.0"
displayName="test remote work"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="julia, MCreator"

[[dependencies.test_remote_work]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




